server:
  port: 8081

spring:
  application:
    name: movie-catalog-service
  profiles:
    active:
    - dev
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
         